# Generated by Django 2.2.5 on 2019-09-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=10)),
                ('organizer', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nik', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('school', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('achievements', models.ManyToManyField(to='athletedb.Achievement')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes_sex', to='athletedb.Sex')),
                ('sports', models.ManyToManyField(to='athletedb.Sport')),
            ],
        ),
    ]
