# Generated by Django 2.2.5 on 2019-09-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('organizer', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='organizer',
        ),
        migrations.AddField(
            model_name='athlete',
            name='birth_place',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements_event', to='athletedb.Event'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='participated_in',
            field=models.ManyToManyField(to='athletedb.Event'),
        ),
    ]
