# Generated by Django 2.2.5 on 2019-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0002_auto_20190925_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
