# Generated by Django 2.2.5 on 2019-09-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0004_auto_20190925_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
