# Generated by Django 2.2.5 on 2019-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0007_auto_20190926_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='nik',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
