# Generated by Django 2.2.5 on 2019-10-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0008_auto_20190926_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementmapping',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievementlist_achievementmapping', to='athletedb.AchievementList'),
        ),
        migrations.AlterField(
            model_name='achievementmapping',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes_achievementmapping', to='athletedb.Athlete'),
        ),
        migrations.AlterField(
            model_name='achievementmapping',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_achievementmapping', to='athletedb.Event'),
        ),
    ]
