# Generated by Django 2.2.5 on 2019-10-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0009_auto_20191001_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'Atlet'},
        ),
    ]
