# Generated by Django 2.2.5 on 2019-10-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0010_auto_20191003_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'Atlet', 'verbose_name_plural': 'Atlet'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Jenis Kelamin', 'verbose_name_plural': 'Jenis Kelamin'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Cabang Olahraga', 'verbose_name_plural': 'Cabang Olahraga'},
        ),
    ]
