# Generated by Django 2.2.5 on 2019-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0011_auto_20191003_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='alamat'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='umur'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='tanggal lahir'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_place',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='tempat lahir'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nama'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='umur'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='school',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='sekolah'),
        ),
    ]
