# Generated by Django 2.2.5 on 2019-10-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0012_auto_20191004_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2, null=True, verbose_name='golongan darah'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sports',
            field=models.ManyToManyField(to='athletedb.Sport', verbose_name='Cabang Olahraga'),
        ),
    ]
