# Generated by Django 2.2.5 on 2019-10-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0013_auto_20191004_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes_sex', to='athletedb.Sex', verbose_name='Jenis Kelamin'),
        ),
    ]
