# Generated by Django 2.2.5 on 2019-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0014_auto_20191004_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, choices=[('laki', 'Laki - laki'), ('perem', 'Perempuan')], default='laki', max_length=20, null=True, verbose_name='Jenis Kelamin'),
        ),
    ]
