# Generated by Django 2.2.5 on 2019-10-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0015_auto_20191008_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, choices=[('laki', 'Laki - laki'), ('perem', 'Perempuan')], default='a', max_length=20, null=True, verbose_name='Jenis Kelamin'),
        ),
    ]
