# Generated by Django 2.2.5 on 2019-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0017_auto_20191008_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, choices=[('Laki - laki', 'Laki - laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True, verbose_name='Jenis Kelamin'),
        ),
    ]
