# Generated by Django 2.2.5 on 2019-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0018_auto_20191008_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='ktp',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
