# Generated by Django 2.2.5 on 2019-10-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0021_auto_20191010_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(blank=True, default='images/pasfoto/default_photo.jpg', null=True, upload_to='images/pasfoto/', verbose_name='Pasfoto'),
        ),
    ]
