# Generated by Django 2.2.5 on 2019-10-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0023_auto_20191011_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Prestasi', 'verbose_name_plural': 'Prestasi'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.CharField(blank=True, choices=[('Tingkat Kota (Porkot)', 'Tingkat Kota (Porkot)'), ('Tingkat Daerah (Porda)', 'Tingkat Daerah (Porda)'), ('Tingkat Provinsi (Porprov)', 'Tingkat Provinsi (Porprov)'), ('Tingkat Nasional (PON)', 'Tingkat Nasional (PON)'), ('Tingkat Dunia (Kejurda)', 'Tingkat Dunia (Kejurda)')], default=None, max_length=255, null=True, verbose_name='Tingkat kejuaraan'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='result',
            field=models.CharField(blank=True, choices=[('Juara 1', 'Juara 1'), ('Juara 2', 'Juara 2'), ('Juara 3', 'Juara 3'), ('Peserta', 'Peserta')], default=None, max_length=10, null=True, verbose_name='Hasil'),
        ),
    ]
