# Generated by Django 2.2.5 on 2019-10-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0025_auto_20191011_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='athlete',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='athletedb.Athlete'),
        ),
    ]
