# Generated by Django 2.2.5 on 2019-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0026_auto_20191012_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='no. telfon'),
        ),
    ]
