# Generated by Django 2.2.5 on 2020-01-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0028_auto_20191106_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
    ]
