# Generated by Django 2.2.13 on 2021-09-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletedb', '0030_auto_20210918_2009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievement',
            table='athletedb_achievement',
        ),
        migrations.AlterModelTable(
            name='achievementlist',
            table='athletedb_achievementlist',
        ),
        migrations.AlterModelTable(
            name='achievementmapping',
            table='athletedb_achievementmapping',
        ),
        migrations.AlterModelTable(
            name='athlete',
            table='athletedb_athlete',
        ),
        migrations.AlterModelTable(
            name='athletesports',
            table='athletedb_athletesports',
        ),
        migrations.AlterModelTable(
            name='event',
            table='athletedb_event',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='athletedb_sport',
        ),
    ]
